/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Reports;

import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import view.InputCheck;
import view.UserMenu;
import view.ViewLogic;

/**
 *
 *
 */
public class FindVehicleInCity extends javax.swing.JInternalFrame {
    private static ViewLogic view;
    private UserMenu um;
    /**
     * Creates new form GetAllWarehousesInManufacturerCountry
     */
    public FindVehicleInCity() {
        initComponents();
        view=ViewLogic.getInstance();
    }

    public FindVehicleInCity(UserMenu um) {
        initComponents();
        view=ViewLogic.getInstance();
        this.um=um;
        languageOpening();
        um.getLanguageComboBox().addActionListener(new java.awt.event.ActionListener(){
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             languageActionPerformed(evt);
         }
  });
        
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        countryText = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        tableLayeredPane = new javax.swing.JLayeredPane();
        resTableScrollPane = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        export = new javax.swing.JButton();
        cityLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        modelNameText = new javax.swing.JTextField();
        modelNameLabel = new javax.swing.JLabel();
        run = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        countryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/Reports/Bundle"); // NOI18N
        countryLabel.setText(bundle.getString("FindVehicleInCity.countryLabel.text")); // NOI18N
        countryLabel.setToolTipText(bundle.getString("FindVehicleInCity.countryLabel.toolTipText")); // NOI18N

        tableLayeredPane.setVisible(false);
        tableLayeredPane.setEnabled(false);

        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VIN", "Model Name", "Vehicle Type", "HP", "Top Speed", "Number of Seats", "Automatic", "Production Cost", "Entered Production", "Production Plan - Serial Number", "Production Plan Type - Serial Number", "Production Plan Type - Number of Slots"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resTable.getTableHeader().setReorderingAllowed(false);
        resTableScrollPane.setViewportView(resTable);

        export.setText(bundle.getString("FindVehicleInCity.export.text")); // NOI18N
        export.setToolTipText(bundle.getString("FindVehicleInCity.export.toolTipText")); // NOI18N
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        export.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exportKeyPressed(evt);
            }
        });

        tableLayeredPane.setLayer(resTableScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tableLayeredPane.setLayer(export, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tableLayeredPaneLayout = new javax.swing.GroupLayout(tableLayeredPane);
        tableLayeredPane.setLayout(tableLayeredPaneLayout);
        tableLayeredPaneLayout.setHorizontalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addComponent(resTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 141, Short.MAX_VALUE))
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(export)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableLayeredPaneLayout.setVerticalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(resTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(export)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        cityLabel.setText(bundle.getString("FindVehicleInCity.cityLabel.text")); // NOI18N
        cityLabel.setToolTipText(bundle.getString("FindVehicleInCity.cityLabel.toolTipText")); // NOI18N

        cityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextActionPerformed(evt);
            }
        });

        modelNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameTextActionPerformed(evt);
            }
        });

        modelNameLabel.setText(bundle.getString("FindVehicleInCity.modelNameLabel.text")); // NOI18N
        modelNameLabel.setToolTipText(bundle.getString("FindVehicleInCity.modelNameLabel.toolTipText")); // NOI18N

        run.setText(bundle.getString("FindVehicleInCity.run.text")); // NOI18N
        run.setToolTipText(bundle.getString("FindVehicleInCity.run.toolTipText")); // NOI18N
        run.setEnabled(false);
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                runKeyPressed(evt);
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(countryText,cityText,modelNameText,run);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(countryText,cityText,modelNameText,run);

            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(countryText,cityText,modelNameText,run);
            }
        };
        countryText.getDocument().addDocumentListener(docListener);
        cityText.getDocument().addDocumentListener(docListener);
        modelNameText.getDocument().addDocumentListener(docListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableLayeredPane)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countryLabel)
                    .addComponent(cityLabel)
                    .addComponent(modelNameLabel))
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172)
                .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNameLabel)
                    .addComponent(modelNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tableLayeredPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextActionPerformed
        if (run.isEnabled())
        runActionPerformed(evt);
    }//GEN-LAST:event_countryTextActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        String country=countryText.getText();
        String city=cityText.getText();
        String model=modelNameText.getText();
        ClearTableRows();
        view.FindVehicleInCityQueryRun(country, city, model, resTable, tableLayeredPane,um.getLanguageComboBox());
    }//GEN-LAST:event_runActionPerformed

    private void runKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_runKeyPressed
         int key=evt.getKeyCode();
          ActionEvent ae = new ActionEvent(evt.getSource(), evt.getID(), evt.paramString());
          if(key==KeyEvent.VK_ENTER && run.isEnabled())        
          runActionPerformed(ae);
            run.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
        
    }//GEN-LAST:event_runKeyPressed

    private void cityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextActionPerformed
         if (run.isEnabled())
        runActionPerformed(evt);
    }//GEN-LAST:event_cityTextActionPerformed

    private void modelNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameTextActionPerformed
         if (run.isEnabled())
        runActionPerformed(evt);
    }//GEN-LAST:event_modelNameTextActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        try {
            String str=cityText.getText();
            str=InputCheck.IllegalFileChars(str);
            view.writeCSVfile(resTable, "FindVehicleInCity", str);
            view.ExportSuccess("FindVehicleInCity", str,um.getLanguageComboBox());
        } catch (IOException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        } catch (ClassNotFoundException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        } catch (SQLException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        }
    }//GEN-LAST:event_exportActionPerformed

    private void exportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exportKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportKeyPressed
private void emptyFields(JTextField countryText , JTextField cityText, JTextField modelNameText, JButton run){
             if (countryText.getText().isEmpty() || cityText.getText().isEmpty() || modelNameText.getText().isEmpty())
                run.setEnabled(false);
             else
                run.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
private void ClearTableRows()
{
    DefaultTableModel dm = (DefaultTableModel) resTable.getModel();
        int rowCount = dm.getRowCount();
        for (int i=rowCount-1; i>=0 ; i--)
            dm.removeRow(i);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindVehicleInCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindVehicleInCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindVehicleInCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindVehicleInCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindVehicleInCity().setVisible(true);
            }
        });
    }

    private void languageOpening()
{
    if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  countryLabel.setText(r.getString("FindVehicleInCity.countryLabel.text"));
                  cityLabel.setText(r.getString("FindVehicleInCity.cityLabel.text"));
                  modelNameLabel.setText(r.getString("FindVehicleInCity.modelNameLabel.text"));
                  export.setText(r.getString("FindVehicleInCity.export.text"));
                  export.setToolTipText(r.getString("FindVehicleInCity.export.toolTipText")); 
                  run.setText(r.getString("FindVehicleInCity.run.text"));
                  hebTableHeaders();
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  countryLabel.setText(r.getString("FindVehicleInCity.countryLabel.text"));
                  cityLabel.setText(r.getString("FindVehicleInCity.cityLabel.text"));
                  modelNameLabel.setText(r.getString("FindVehicleInCity.modelNameLabel.text"));
                  export.setText(r.getString("FindVehicleInCity.export.text"));
                  export.setToolTipText(r.getString("FindVehicleInCity.export.toolTipText")); 
                  run.setText(r.getString("FindVehicleInCity.run.text"));
                  engTableHeaders();
              }
}
  
    private void languageActionPerformed(java.awt.event.ActionEvent evt) {  
    if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  countryLabel.setText(r.getString("FindVehicleInCity.countryLabel.text"));
                  cityLabel.setText(r.getString("FindVehicleInCity.cityLabel.text"));
                  modelNameLabel.setText(r.getString("FindVehicleInCity.modelNameLabel.text"));
                  export.setText(r.getString("FindVehicleInCity.export.text"));
                  export.setToolTipText(r.getString("FindVehicleInCity.export.toolTipText")); 
                  run.setText(r.getString("FindVehicleInCity.run.text"));
                  hebTableHeaders();
                  this.setTitle("מצא רכב בעיר");
                  resTable.setAutoResizeMode(2);
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  countryLabel.setText(r.getString("FindVehicleInCity.countryLabel.text"));
                  cityLabel.setText(r.getString("FindVehicleInCity.cityLabel.text"));
                  modelNameLabel.setText(r.getString("FindVehicleInCity.modelNameLabel.text"));
                  export.setText(r.getString("FindVehicleInCity.export.text"));
                  export.setToolTipText(r.getString("FindVehicleInCity.export.toolTipText")); 
                  run.setText(r.getString("FindVehicleInCity.run.text"));
                  engTableHeaders();
                  this.setTitle("Find Vehicle in City");
                  resTable.setAutoResizeMode(2);
              }
}
    
    private void engTableHeaders()
{
    String[]engHeaders={"VIN","Model Name","Category", "HP" , "Top Speed", "Number of Seats", "Automatic", "Production Cost", "Entered Production","Production Plan - Serial Number", "Production Plan Type - Serial Number", "Production Plan Type - Number of Slots"};
    for (int i=0;i<engHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(engHeaders[i]);
}

private void hebTableHeaders()
{
    String[]hebHeaders={"מספר הזיהוי של הרכב","שם הדגם","קטגוריה", "כח סוס" , "מהירות מקסימלית", "מספר מושבים", "אוטומט", "מכיר יצור", "תאריך כניסה ליצור","תכנית יצור -מספר סידורי", "סוג תכנית יצור-מספר סידורי", "סוג תכנית יצור-מספר סלוטים"};
    for (int i=0;i<hebHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(hebHeaders[i]);
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryText;
    private javax.swing.JButton export;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modelNameLabel;
    private javax.swing.JTextField modelNameText;
    private javax.swing.JTable resTable;
    private javax.swing.JScrollPane resTableScrollPane;
    private javax.swing.JButton run;
    private javax.swing.JLayeredPane tableLayeredPane;
    // End of variables declaration//GEN-END:variables
}
