/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Reports;

import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import view.InputCheck;
import view.UserMenu;
import view.ViewLogic;

/**
 *
 *
 */
public class GetAllWarehousesInManufacturerCountry extends javax.swing.JInternalFrame {
    private static ViewLogic view;
    private UserMenu um;
    /**
     * Creates new form GetAllWarehousesInManufacturerCountry
     */
    public GetAllWarehousesInManufacturerCountry() {
        initComponents();
        view=ViewLogic.getInstance();
    }
    
public GetAllWarehousesInManufacturerCountry(UserMenu um) {
        initComponents();
        view=ViewLogic.getInstance();
        this.um=um;
        languageOpening();
         um.getLanguageComboBox().addActionListener(new java.awt.event.ActionListener(){
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             languageActionPerformed(evt);
         }
  });
          
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manufacturerText = new javax.swing.JTextField();
        manufacturerLabel = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        tableLayeredPane = new javax.swing.JLayeredPane();
        resTableScrollPane = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        export = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));

        manufacturerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerTextActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/Reports/Bundle"); // NOI18N
        manufacturerLabel.setText(bundle.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.text")); // NOI18N
        manufacturerLabel.setToolTipText(bundle.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.toolTipText")); // NOI18N

        run.setText(bundle.getString("GetAllWarehousesInManufacturerCountry.run.text")); // NOI18N
        run.setToolTipText(bundle.getString("GetAllWarehousesInManufacturerCountry.run.toolTipText")); // NOI18N
        run.setEnabled(false);
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                runKeyPressed(evt);
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(manufacturerText,run);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(manufacturerText,run);

            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(manufacturerText,run);
            }
        };
        manufacturerText.getDocument().addDocumentListener(docListener);

        tableLayeredPane.setVisible(false);
        tableLayeredPane.setEnabled(false);

        resTable.setAutoCreateRowSorter(true);
        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Warehouse Number", "Country", "City", "Street", "House Number", "ZIP Code", "Max Parts Stored", "Max Vehicles Stored", "Current Number of Parts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resTable.getTableHeader().setReorderingAllowed(false);
        resTableScrollPane.setViewportView(resTable);

        export.setText(bundle.getString("GetAllWarehousesInManufacturerCountry.export.text")); // NOI18N
        export.setToolTipText(bundle.getString("GetAllWarehousesInManufacturerCountry.export.toolTipText")); // NOI18N
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        tableLayeredPane.setLayer(resTableScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tableLayeredPane.setLayer(export, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tableLayeredPaneLayout = new javax.swing.GroupLayout(tableLayeredPane);
        tableLayeredPane.setLayout(tableLayeredPaneLayout);
        tableLayeredPaneLayout.setHorizontalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resTableScrollPane))
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(export)
                .addGap(0, 493, Short.MAX_VALUE))
        );
        tableLayeredPaneLayout.setVerticalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addComponent(resTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(export)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(manufacturerLabel)
                        .addGap(78, 78, 78)
                        .addComponent(manufacturerText, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerLabel)
                    .addComponent(run))
                .addGap(30, 30, 30)
                .addComponent(tableLayeredPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manufacturerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerTextActionPerformed
        if (run.isEnabled())
        runActionPerformed(evt);
    }//GEN-LAST:event_manufacturerTextActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        String manu=manufacturerText.getText();
        ClearTableRows();
        view.GetAllWarehousesInManufacturerCountryQueryRun(manu,resTable,tableLayeredPane,um.getLanguageComboBox());     
    }//GEN-LAST:event_runActionPerformed

    private void runKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_runKeyPressed
         int key=evt.getKeyCode();
          ActionEvent ae = new ActionEvent(evt.getSource(), evt.getID(), evt.paramString());
          if(key==KeyEvent.VK_ENTER && run.isEnabled())        
          runActionPerformed(ae);
            run.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
        
    }//GEN-LAST:event_runKeyPressed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        try {
         String str=manufacturerText.getText();
         str=InputCheck.IllegalFileChars(str);
         view.writeCSVfile(resTable, "GetAllWarehousesInManufacturerCountry", str);
         view.ExportSuccess("GetAllWarehousesInManufacturerCountry", str,um.getLanguageComboBox());
     } catch (IOException ex) {
         view.ExportFailed(um.getLanguageComboBox());
     } catch (ClassNotFoundException ex) {
         view.ExportFailed(um.getLanguageComboBox());
     } catch (SQLException ex) {
         view.ExportFailed(um.getLanguageComboBox());
     }
    }//GEN-LAST:event_exportActionPerformed
private void emptyFields(JTextField manufacturerText ,JButton run){
             if (manufacturerText.getText().isEmpty())
                run.setEnabled(false);
             else
                run.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
private void ClearTableRows()
{
    DefaultTableModel dm = (DefaultTableModel) resTable.getModel();
        int rowCount = dm.getRowCount();
        for (int i=rowCount-1; i>=0 ; i--)
            dm.removeRow(i);
}

private void languageActionPerformed(java.awt.event.ActionEvent evt) {  
    if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  manufacturerLabel.setText(r.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.text"));
                  export.setText(r.getString("GetAllWarehousesInManufacturerCountry.export.text"));
                  export.setToolTipText(r.getString("GetAllWarehousesInManufacturerCountry.export.toolTipText")); 
                  run.setText(r.getString("GetAllWarehousesInManufacturerCountry.run.text"));
                  hebTableHeaders();
                  this.setTitle("השג את כל המחסנים במדינת היצרן");
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  manufacturerLabel.setText(r.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.text"));
                  export.setText(r.getString("GetAllWarehousesInManufacturerCountry.export.text"));
                  export.setToolTipText(r.getString("GetAllWarehousesInManufacturerCountry.export.toolTipText")); 
                  run.setText(r.getString("GetAllWarehousesInManufacturerCountry.run.text"));
                  engTableHeaders();
                  this.setTitle("Get All Warehouses in Manufacturer Country");
              }
}

private void languageOpening()
{
    if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  manufacturerLabel.setText(r.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.text"));
                  export.setText(r.getString("GetAllWarehousesInManufacturerCountry.export.text"));
                  export.setToolTipText(r.getString("GetAllWarehousesInManufacturerCountry.export.toolTipText")); 
                  run.setText(r.getString("GetAllWarehousesInManufacturerCountry.run.text"));
                  hebTableHeaders();
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  manufacturerLabel.setText(r.getString("GetAllWarehousesInManufacturerCountry.manufacturerLabel.text"));
                  export.setText(r.getString("GetAllWarehousesInManufacturerCountry.export.text"));
                  export.setToolTipText(r.getString("GetAllWarehousesInManufacturerCountry.export.toolTipText")); 
                  run.setText(r.getString("GetAllWarehousesInManufacturerCountry.run.text"));
                  engTableHeaders();
              }
}

private void engTableHeaders()
{
    String[]engHeaders={"Warehouse Number","Country", "City" , "Street" , "House Number", "ZIP Code", "Max Parts Stored", "Max Vehicles Stored", "Current Number of Parts"};
    for (int i=0;i<engHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(engHeaders[i]);
}

private void hebTableHeaders()
{
    String[]hebHeaders={"מספר מחסן","מדינה", "עיר" , "רחוב" , "מספר בית", "מיקוד", "מכסת חלקים לאחסון", "מכסת רכבים לאחסון", "כמות החלקים הנוכחית"};
    for (int i=0;i<hebHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(hebHeaders[i]);
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetAllWarehousesInManufacturerCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetAllWarehousesInManufacturerCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetAllWarehousesInManufacturerCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetAllWarehousesInManufacturerCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetAllWarehousesInManufacturerCountry().setVisible(true);

            }
        });
    }

    public JButton getExport() {
        return export;
    }

    public JLabel getManufacturerLabel() {
        return manufacturerLabel;
    }

    public JButton getRun() {
        return run;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton export;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField manufacturerText;
    private javax.swing.JTable resTable;
    private javax.swing.JScrollPane resTableScrollPane;
    private javax.swing.JButton run;
    private javax.swing.JLayeredPane tableLayeredPane;
    // End of variables declaration//GEN-END:variables
}
