/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Reports;

import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import view.InputCheck;
import view.UserMenu;
import view.ViewLogic;

/**
 *
 *
 */
public class GetMissingPartsForProductionPlan extends javax.swing.JInternalFrame {
    private static ViewLogic view;
    private UserMenu um;
    /**
     * Creates new form GetAllWarehousesInManufacturerCountry
     */
    public GetMissingPartsForProductionPlan() {
        initComponents();
        view=ViewLogic.getInstance();
    }

    public GetMissingPartsForProductionPlan(UserMenu um) {
        initComponents();
        view=ViewLogic.getInstance();
        this.um=um;
        languageOpening();
         um.getLanguageComboBox().addActionListener(new java.awt.event.ActionListener(){
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             languageActionPerformed(evt);
         }
  });
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productionPlanNumberText = new javax.swing.JTextField();
        productionPlanNumberLabel = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        tableLayeredPane = new javax.swing.JLayeredPane();
        resTableScrollPane = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        export = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/Reports/Bundle"); // NOI18N
        productionPlanNumberText.setToolTipText(bundle.getString("GetMissingPartsForProductionPlan.productionPlanNumberText.toolTipText")); // NOI18N
        productionPlanNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionPlanNumberTextActionPerformed(evt);
            }
        });

        productionPlanNumberLabel.setText(bundle.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.text")); // NOI18N
        productionPlanNumberLabel.setToolTipText(bundle.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.toolTipText")); // NOI18N

        run.setText(bundle.getString("GetMissingPartsForProductionPlan.run.text")); // NOI18N
        run.setToolTipText(bundle.getString("GetMissingPartsForProductionPlan.run.toolTipText")); // NOI18N
        run.setEnabled(false);
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                runKeyPressed(evt);
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(productionPlanNumberText,run);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(productionPlanNumberText,run);

            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(productionPlanNumberText,run);
            }
        };
        productionPlanNumberText.getDocument().addDocumentListener(docListener);

        tableLayeredPane.setVisible(false);
        tableLayeredPane.setEnabled(false);

        resTable.setAutoCreateRowSorter(true);
        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part Type Number", "Part Type Name", "Category", "Production Cost", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resTable.getTableHeader().setReorderingAllowed(false);
        resTableScrollPane.setViewportView(resTable);

        export.setText(bundle.getString("GetMissingPartsForProductionPlan.export.text")); // NOI18N
        export.setToolTipText(bundle.getString("GetMissingPartsForProductionPlan.export.toolTipText")); // NOI18N
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        export.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exportKeyPressed(evt);
            }
        });

        tableLayeredPane.setLayer(resTableScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tableLayeredPane.setLayer(export, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tableLayeredPaneLayout = new javax.swing.GroupLayout(tableLayeredPane);
        tableLayeredPane.setLayout(tableLayeredPaneLayout);
        tableLayeredPaneLayout.setHorizontalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resTableScrollPane)
                .addContainerGap())
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(export)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        tableLayeredPaneLayout.setVerticalGroup(
            tableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(export)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(productionPlanNumberLabel)
                        .addGap(102, 102, 102)
                        .addComponent(productionPlanNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tableLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productionPlanNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productionPlanNumberLabel)
                    .addComponent(run))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableLayeredPane)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productionPlanNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionPlanNumberTextActionPerformed
        if (run.isEnabled())
        runActionPerformed(evt);
    }//GEN-LAST:event_productionPlanNumberTextActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        ClearTableRows();
        view.GetMissingPartsForProductionPlanQueryRun(productionPlanNumberLabel.getText(),productionPlanNumberText.getText(), resTable, tableLayeredPane,um.getLanguageComboBox());
    }//GEN-LAST:event_runActionPerformed

    private void runKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_runKeyPressed
         int key=evt.getKeyCode();
          ActionEvent ae = new ActionEvent(evt.getSource(), evt.getID(), evt.paramString());
          if(key==KeyEvent.VK_ENTER && run.isEnabled())        
          runActionPerformed(ae);
            run.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
        
    }//GEN-LAST:event_runKeyPressed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        try {
            String str=productionPlanNumberText.getText();
            str=InputCheck.IllegalFileChars(str);
            view.writeCSVfile(resTable, "GetMissingPartsForProductionPlan", str);
            view.ExportSuccess("GetMissingPartsForProductionPlan", str,um.getLanguageComboBox());
        } catch (IOException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        } catch (ClassNotFoundException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        } catch (SQLException ex) {
            view.ExportFailed(um.getLanguageComboBox());
        }
    }//GEN-LAST:event_exportActionPerformed

    private void exportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exportKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportKeyPressed
private void emptyFields(JTextField manufacturerText ,JButton run){
             if (manufacturerText.getText().isEmpty())
                run.setEnabled(false);
             else
                run.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
private void ClearTableRows()
{
    DefaultTableModel dm = (DefaultTableModel) resTable.getModel();
        int rowCount = dm.getRowCount();
        for (int i=rowCount-1; i>=0 ; i--)
            dm.removeRow(i);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetMissingPartsForProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetMissingPartsForProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetMissingPartsForProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetMissingPartsForProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMissingPartsForProductionPlan().setVisible(true);
            }
        });
    }

  private void languageOpening()
{
    if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  productionPlanNumberLabel.setText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.text"));
                  productionPlanNumberLabel.setToolTipText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberText.toolTipText"));
                  export.setText(r.getString("GetMissingPartsForProductionPlan.export.text"));
                  export.setToolTipText(r.getString("GetMissingPartsForProductionPlan.export.toolTipText")); 
                  run.setText(r.getString("GetMissingPartsForProductionPlan.run.text"));
                  hebTableHeaders();
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  productionPlanNumberLabel.setText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.text"));
                  productionPlanNumberLabel.setToolTipText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberText.toolTipText"));
                  export.setText(r.getString("GetMissingPartsForProductionPlan.export.text"));
                  export.setToolTipText(r.getString("GetMissingPartsForProductionPlan.export.toolTipText")); 
                  run.setText(r.getString("GetMissingPartsForProductionPlan.run.text"));
                  engTableHeaders();
              }
}  
   
  private void languageActionPerformed(java.awt.event.ActionEvent evt) {  
   if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              {
                  Locale l = new Locale("iw", "IL");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  productionPlanNumberLabel.setText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.text"));
                  productionPlanNumberLabel.setToolTipText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberText.toolTipText"));
                  export.setText(r.getString("GetMissingPartsForProductionPlan.export.text"));
                  export.setToolTipText(r.getString("GetMissingPartsForProductionPlan.export.toolTipText")); 
                  run.setText(r.getString("GetMissingPartsForProductionPlan.run.text"));
                  hebTableHeaders();
                  this.setTitle("השג חלקים חסרים לתכנית ייצור");
                  resTable.setAutoResizeMode(2);
              }
             else if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              {
                  Locale l = new Locale("en", "US");
                  ResourceBundle r = ResourceBundle.getBundle("view.Reports/Bundle",l);
                  productionPlanNumberLabel.setText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberLabel.text"));
                  productionPlanNumberLabel.setToolTipText(r.getString("GetMissingPartsForProductionPlan.productionPlanNumberText.toolTipText"));
                  export.setText(r.getString("GetMissingPartsForProductionPlan.export.text"));
                  export.setToolTipText(r.getString("GetMissingPartsForProductionPlan.export.toolTipText")); 
                  run.setText(r.getString("GetMissingPartsForProductionPlan.run.text"));
                  engTableHeaders();
                  this.setTitle("Get Missing Parts For Production Plan");
                  resTable.setAutoResizeMode(2);         
              }
}
  
private void engTableHeaders()
{
    String[]engHeaders={"Part Type Number","Part Type Name", "Category" , "Production Cost","Amount"};
    for (int i=0;i<engHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(engHeaders[i]);
}

private void hebTableHeaders()
{
    String[]hebHeaders={"מספר סוג החלק","שם סוג החלק", "קטגוריה" , "מחיר יצור","כמות"};
    for (int i=0;i<hebHeaders.length;i++)
    resTable.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(hebHeaders[i]);
}  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton export;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productionPlanNumberLabel;
    private javax.swing.JTextField productionPlanNumberText;
    private javax.swing.JTable resTable;
    private javax.swing.JScrollPane resTableScrollPane;
    private javax.swing.JButton run;
    private javax.swing.JLayeredPane tableLayeredPane;
    // End of variables declaration//GEN-END:variables
}
