/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.MyPanels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import javax.swing.JRadioButton;
import view.UserMenu;

/**
 *
 *
 */
public class AddEmployee extends javax.swing.JPanel {
    private UserMenu um;
     GridBagLayout layout= new GridBagLayout();
     AddGuard g;
     AddShiftM sm;
     AddWorker worker;
     
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee(UserMenu um) {
        initComponents();
        this.um=um;
        g=new AddGuard(um);
        worker= new AddWorker(um);
        sm= new AddShiftM(um);
        InnerDynamicPanel.setLayout(layout);
         GridBagConstraints c= new GridBagConstraints();
         c.gridx=0;
         c.gridy=0;
         InnerDynamicPanel.add(g,c);
         c.gridx=0;
         c.gridy=0;
         InnerDynamicPanel.add(sm,c);
         c.gridx=0;
         c.gridy=0;
         InnerDynamicPanel.add(worker,c);
          g.setVisible(false);
          sm.setVisible(false);
          worker.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        InnerDynamicPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        w_btn = new javax.swing.JRadioButton();
        sm_btn = new javax.swing.JRadioButton();
        g_btn = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(235, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InnerDynamicPanel.setBackground(new java.awt.Color(235, 255, 255));

        javax.swing.GroupLayout InnerDynamicPanelLayout = new javax.swing.GroupLayout(InnerDynamicPanel);
        InnerDynamicPanel.setLayout(InnerDynamicPanelLayout);
        InnerDynamicPanelLayout.setHorizontalGroup(
            InnerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        InnerDynamicPanelLayout.setVerticalGroup(
            InnerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        add(InnerDynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 650));

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));

        w_btn.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(w_btn);
        w_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        w_btn.setForeground(new java.awt.Color(102, 102, 102));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/MyPanels/Bundle"); // NOI18N
        w_btn.setText(bundle.getString("AddEmployee.w_btn.text")); // NOI18N
        w_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w_btnMouseClicked(evt);
            }
        });
        w_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w_btnActionPerformed(evt);
            }
        });

        sm_btn.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(sm_btn);
        sm_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sm_btn.setForeground(new java.awt.Color(102, 102, 102));
        sm_btn.setText(bundle.getString("AddEmployee.sm_btn.text")); // NOI18N
        sm_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sm_btnMouseClicked(evt);
            }
        });
        sm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_btnActionPerformed(evt);
            }
        });

        g_btn.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(g_btn);
        g_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        g_btn.setForeground(new java.awt.Color(102, 102, 102));
        g_btn.setText(bundle.getString("AddEmployee.g_btn.text")); // NOI18N
        g_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g_btnMouseClicked(evt);
            }
        });
        g_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(g_btn)
                .addGap(45, 45, 45)
                .addComponent(sm_btn)
                .addGap(45, 45, 45)
                .addComponent(w_btn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g_btn)
                    .addComponent(sm_btn)
                    .addComponent(w_btn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 718, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void g_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_btnActionPerformed
        
    }//GEN-LAST:event_g_btnActionPerformed

    private void sm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sm_btnActionPerformed

    private void w_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w_btnActionPerformed

    private void g_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g_btnMouseClicked
          g.setVisible(true);
          sm.setVisible(false);
          worker.setVisible(false);
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
          UserMenu.getLabel_Add().setText("Add Guard");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                UserMenu.getLabel_Add().setText("הוסף שומר");
    }//GEN-LAST:event_g_btnMouseClicked

    private void sm_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sm_btnMouseClicked
         g.setVisible(false);
          sm.setVisible(true);
          worker.setVisible(false);
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
          UserMenu.getLabel_Add().setText("Add Shift Manager");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                UserMenu.getLabel_Add().setText("הוסף מנהל משמרת");
    }//GEN-LAST:event_sm_btnMouseClicked

    private void w_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w_btnMouseClicked
          g.setVisible(false);
          sm.setVisible(false);
          worker.setVisible(true);
          if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
          UserMenu.getLabel_Add().setText("Add Worker");
          else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              UserMenu.getLabel_Add().setText("הוסף פועל");
    }//GEN-LAST:event_w_btnMouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        g.setVisible(false);
        sm.setVisible(false);
        worker.setVisible(false);
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_formComponentHidden

    public JRadioButton getG_btn() {
        return g_btn;
    }

    public JRadioButton getSm_btn() {
        return sm_btn;
    }

    public JRadioButton getW_btn() {
        return w_btn;
    }

    public AddGuard getG() {
        return g;
    }

    public AddShiftM getSm() {
        return sm;
    }

    public AddWorker getWorker() {
        return worker;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InnerDynamicPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton g_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton sm_btn;
    private javax.swing.JRadioButton w_btn;
    // End of variables declaration//GEN-END:variables
}
