/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.MyPanels;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.PartType;
import model.User;
import utils.E_UserType;
import utils.E_SecretQuestion;
import view.InputCheck;
import view.UserMenu;
import view.ViewLogic;

/**
 *
 *
 */
public class AddUser extends javax.swing.JPanel {
private static ViewLogic view;
private UserMenu um;
    /**
     * Creates new form AddPartType
     */
    public AddUser(UserMenu um) {
        initComponents();
        view=ViewLogic.getInstance();
        this.um=um;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_AddPart = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        secretAnswerLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        passwordText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        secretAnswerText = new javax.swing.JTextField();
        secretQuestionLabel = new javax.swing.JLabel();
        sqComboBox = new javax.swing.JComboBox<>();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        Panel_AddPart.setBackground(new java.awt.Color(235, 255, 255));
        Panel_AddPart.setPreferredSize(new java.awt.Dimension(758, 300));

        usernameLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(87, 84, 84));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/MyPanels/Bundle"); // NOI18N
        usernameLabel.setText(bundle.getString("AddUser.usernameLabel.text")); // NOI18N

        usernameText.setBackground(new java.awt.Color(235, 255, 255));
        usernameText.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        usernameText.setBorder(null);
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        addPanel.setBackground(new java.awt.Color(204, 204, 204));
        addPanel.setForeground(new java.awt.Color(255, 255, 255));
        addPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPanelMouseExited(evt);
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(usernameText, passwordText, secretAnswerText,addPanel);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(usernameText, passwordText, secretAnswerText,addPanel);
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(usernameText, passwordText, secretAnswerText,addPanel);
            }
        };
        usernameText.getDocument().addDocumentListener(docListener);
        passwordText.getDocument().addDocumentListener(docListener);
        secretAnswerText.getDocument().addDocumentListener(docListener);

        jLabel25.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(bundle.getString("AddUser.jLabel25.text")); // NOI18N

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(76, 76, 76))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(11, 11, 11))
        );

        passwordLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(87, 84, 84));
        passwordLabel.setText(bundle.getString("AddUser.passwordLabel.text")); // NOI18N

        typeLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(87, 84, 84));
        typeLabel.setText(bundle.getString("AddUser.typeLabel.text")); // NOI18N

        secretAnswerLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        secretAnswerLabel.setForeground(new java.awt.Color(87, 84, 84));
        secretAnswerLabel.setText(bundle.getString("AddUser.secretAnswerLabel.text")); // NOI18N

        typeComboBox.setBackground(new java.awt.Color(235, 255, 255));
        typeComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeComboBox.setForeground(new java.awt.Color(82, 80, 80));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        typeComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        typeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N

        passwordText.setBackground(new java.awt.Color(235, 255, 255));
        passwordText.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        passwordText.setBorder(null);
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator4.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N

        secretAnswerText.setBackground(new java.awt.Color(235, 255, 255));
        secretAnswerText.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        secretAnswerText.setBorder(null);
        secretAnswerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretAnswerTextActionPerformed(evt);
            }
        });

        secretQuestionLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        secretQuestionLabel.setForeground(new java.awt.Color(87, 84, 84));
        secretQuestionLabel.setText(bundle.getString("AddUser.secretQuestionLabel.text")); // NOI18N

        sqComboBox.setBackground(new java.awt.Color(235, 255, 255));
        sqComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sqComboBox.setForeground(new java.awt.Color(82, 80, 80));
        sqComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pet's name?", "In what city were you born?", "What is your favorite movie?", "What high school did you attend?" }));
        sqComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sqComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sqComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_AddPartLayout = new javax.swing.GroupLayout(Panel_AddPart);
        Panel_AddPart.setLayout(Panel_AddPartLayout);
        Panel_AddPartLayout.setHorizontalGroup(
            Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AddPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secretAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(secretQuestionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addGap(60, 60, 60)
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(secretAnswerText, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addComponent(addPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addComponent(sqComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        Panel_AddPartLayout.setVerticalGroup(
            Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AddPartLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AddPartLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(Panel_AddPartLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secretQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Panel_AddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secretAnswerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AddPartLayout.createSequentialGroup()
                        .addComponent(secretAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(38, 38, 38)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AddPart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AddPart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void secretAnswerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretAnswerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secretAnswerTextActionPerformed

    private void addPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPanelMouseEntered
       view.AddMouseEnter(addPanel);
    }//GEN-LAST:event_addPanelMouseEntered

    private void addPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPanelMouseExited
        view.AddMouseExit(addPanel);
    }//GEN-LAST:event_addPanelMouseExited

    private void addPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPanelMouseClicked

     boolean bool;
     Color c=new Color(204,204,204);
     if (!addPanel.getBackground().equals(c))
     { 
              Object[] options = {"Yes","No"};
              Object[] hebOptions = {"כן","לא"};
            int n=0;
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              n = JOptionPane.showOptionDialog(null, "Are you sure you want to proceed?","Adding confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[1]);
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              n = JOptionPane.showOptionDialog(null, "האם אתה בטוח שברצונך להמשיך?","אימות הוספה",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,hebOptions,hebOptions[1]);    
              if (n==0)
              {
            E_UserType e=null;
            e= InputCheck.TryConvertingStringtoUTEnum(typeComboBox.getSelectedItem().toString(), e);
            if (e==null)
            {
               Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
               JOptionPane.showMessageDialog(null, "Invalid Type!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "סוג שגוי!");
               typeComboBox.grabFocus();
            }
            else
            {
             E_SecretQuestion sq=null;
             sq=InputCheck.ConvertStringtoSQ(sqComboBox.getSelectedItem().toString(), sq);
            if (sq==null)
            {
               Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
               JOptionPane.showMessageDialog(null, "Invalid Question!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "שאלה סודית שגויה!");
               sqComboBox.grabFocus();
            }
            else
            {
            bool=view.controller.addUser(usernameText.getText(),passwordText.getText(), e ,sq ,secretAnswerText.getText());
            if (bool==true)
            {
                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            JOptionPane.showMessageDialog(null, "User added successfully!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "המשתמש הוסף בהצלחה!");
            usernameText.setText("");
            passwordText.setText("");
            typeComboBox.setSelectedIndex(0);
            sqComboBox.setSelectedIndex(0);
            secretAnswerText.setText("");
            }
            else
             {
                User u=view.model.getUsers().get(usernameText.getText());
                if (u!=null)
                {
                    Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                JOptionPane.showMessageDialog(null, "User " + usernameText.getText() + " already exists!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "המשתמש " + usernameText.getText() + " כבר קיים!");
                usernameText.grabFocus();
                }
             }
            }
              }
            
          }
     }
       
     
    }//GEN-LAST:event_addPanelMouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        usernameText.setText("");
        passwordText.setText("");
        typeComboBox.setSelectedIndex(0);
        sqComboBox.setSelectedIndex(0);
        secretAnswerText.setText("");
    }//GEN-LAST:event_formComponentHidden

    private void sqComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqComboBoxActionPerformed

private void emptyFields(JTextField field, JTextField  fieldtwo, JTextField fieldthree,JPanel add){
    
             Color c=null;
             if (field.getText().length()<4 || fieldtwo.getText().length()<4 || fieldthree.getText().length()<4)
             {
                 c=new Color(204,204,204);
                add.setBackground(c);
             }
                else
             {
                 c=new Color(0,102,102);
                add.setBackground(c);
             }
}

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public JLabel getPasswordLabel() {
        return passwordLabel;
    }

    public JLabel getSecretAnswerLabel() {
        return secretAnswerLabel;
    }

    public JLabel getSecretQuestionLabel() {
        return secretQuestionLabel;
    }

    public JLabel getTypeLabel() {
        return typeLabel;
    }

    public JLabel getUsernameLabel() {
        return usernameLabel;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_AddPart;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel secretAnswerLabel;
    private javax.swing.JTextField secretAnswerText;
    private javax.swing.JLabel secretQuestionLabel;
    private javax.swing.JComboBox<String> sqComboBox;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
