/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.MyPanels;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 *
 */
public class DesignPanel extends javax.swing.JPanel {

    /**
     * Creates new form DesignPanel
     */
    public DesignPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundColorLabel = new javax.swing.JLabel();
        sidebarLabel = new javax.swing.JLabel();
        backgroundColorComboBox = new javax.swing.JComboBox<>();
        sidebarColorComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(235, 255, 255));

        backgroundColorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/MyPanels/Bundle"); // NOI18N
        backgroundColorLabel.setText(bundle.getString("DesignPanel.backgroundColorLabel.text")); // NOI18N

        sidebarLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sidebarLabel.setText(bundle.getString("DesignPanel.sidebarLabel.text")); // NOI18N

        backgroundColorComboBox.setBackground(new java.awt.Color(235, 255, 255));
        backgroundColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Blue", "Red", "Black", "Yellow", "Pink" }));

        sidebarColorComboBox.setBackground(new java.awt.Color(235, 255, 255));
        sidebarColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Blue", "Red", "Black", "Yellow", "Pink" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundColorLabel)
                    .addComponent(sidebarLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundColorLabel)
                    .addComponent(backgroundColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidebarLabel)
                    .addComponent(sidebarColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getjComboBoxBackground() {
        return backgroundColorComboBox;
    }

    public JComboBox<String> getjComboBoxSideBar() {
        return sidebarColorComboBox;
    }

    public JLabel getBackgroundColorLabel() {
        return backgroundColorLabel;
    }

    public JLabel getSidebarLabel() {
        return sidebarLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> backgroundColorComboBox;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JComboBox<String> sidebarColorComboBox;
    private javax.swing.JLabel sidebarLabel;
    // End of variables declaration//GEN-END:variables
}
