/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.MyPanels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import view.UserMenu;

/**
 *
 *
 */
public class Options extends javax.swing.JPanel {
    private UserMenu um;
    GridBagLayout layout= new GridBagLayout();
    Notification notification;
    DesignPanel design;
    VolumePanel volume;
    lockPanel lock;
    

    /**
     * Creates new form Options
     */
    public Options(UserMenu um) {
        initComponents();
        this.um=um;
        notification= new Notification(um);
        design= new DesignPanel() ;
        volume= new VolumePanel() ;
        lock= new lockPanel() ;
          changeDynamicPanel.setLayout(layout);
          volumedynamicPanel.setLayout(layout);
          designdynamicPanel.setLayout(layout);
          lockdynamicPanel.setLayout(layout);
         GridBagConstraints c= new GridBagConstraints();
         c.gridx=0;
         c.gridy=0;
         changeDynamicPanel.add(notification,c);
         c.gridx=0;
         c.gridy=0;
         volumedynamicPanel.add(volume,c);
         c.gridx=0;
         c.gridy=0;
         designdynamicPanel.add(design,c);
         c.gridx=0;
         c.gridy=0;
         lockdynamicPanel.add(lock,c);
          c.gridx=0;
         c.gridy=0;
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(true);
        icon_designPanel.setVisible(true);
        icon_lockPane.setVisible(true);
        icon_volumePanel.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        volumedynamicPanel = new javax.swing.JPanel();
        icon_volumePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lockdynamicPanel = new javax.swing.JPanel();
        icon_lockPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        changeDynamicPanel = new javax.swing.JPanel();
        icon_notificiationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        designdynamicPanel = new javax.swing.JPanel();
        icon_designPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 255, 255));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        volumedynamicPanel.setBackground(new java.awt.Color(235, 255, 255));
        volumedynamicPanel.setPreferredSize(new java.awt.Dimension(342, 227));
        volumedynamicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumedynamicPanelMouseClicked(evt);
            }
        });

        icon_volumePanel.setBackground(new java.awt.Color(0, 153, 153));
        icon_volumePanel.setToolTipText("Adjust volume");
        icon_volumePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_volumePanelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/002-volume.png"))); // NOI18N

        javax.swing.GroupLayout icon_volumePanelLayout = new javax.swing.GroupLayout(icon_volumePanel);
        icon_volumePanel.setLayout(icon_volumePanelLayout);
        icon_volumePanelLayout.setHorizontalGroup(
            icon_volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_volumePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        icon_volumePanelLayout.setVerticalGroup(
            icon_volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_volumePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout volumedynamicPanelLayout = new javax.swing.GroupLayout(volumedynamicPanel);
        volumedynamicPanel.setLayout(volumedynamicPanelLayout);
        volumedynamicPanelLayout.setHorizontalGroup(
            volumedynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumedynamicPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(icon_volumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        volumedynamicPanelLayout.setVerticalGroup(
            volumedynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volumedynamicPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_volumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        lockdynamicPanel.setBackground(new java.awt.Color(235, 255, 255));
        lockdynamicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockdynamicPanelMouseClicked(evt);
            }
        });

        icon_lockPane.setBackground(new java.awt.Color(0, 153, 153));
        icon_lockPane.setToolTipText("Lock features");
        icon_lockPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_lockPaneMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/003-unlock.png"))); // NOI18N

        javax.swing.GroupLayout icon_lockPaneLayout = new javax.swing.GroupLayout(icon_lockPane);
        icon_lockPane.setLayout(icon_lockPaneLayout);
        icon_lockPaneLayout.setHorizontalGroup(
            icon_lockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_lockPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        icon_lockPaneLayout.setVerticalGroup(
            icon_lockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_lockPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lockdynamicPanelLayout = new javax.swing.GroupLayout(lockdynamicPanel);
        lockdynamicPanel.setLayout(lockdynamicPanelLayout);
        lockdynamicPanelLayout.setHorizontalGroup(
            lockdynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lockdynamicPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(icon_lockPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        lockdynamicPanelLayout.setVerticalGroup(
            lockdynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lockdynamicPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(icon_lockPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        changeDynamicPanel.setBackground(new java.awt.Color(235, 255, 255));
        changeDynamicPanel.setPreferredSize(new java.awt.Dimension(342, 259));
        changeDynamicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeDynamicPanelMouseClicked(evt);
            }
        });

        icon_notificiationPanel.setBackground(new java.awt.Color(0, 153, 153));
        icon_notificiationPanel.setToolTipText("Add a message to the system");
        icon_notificiationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_notificiationPanelMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/004-speech-bubble.png"))); // NOI18N

        javax.swing.GroupLayout icon_notificiationPanelLayout = new javax.swing.GroupLayout(icon_notificiationPanel);
        icon_notificiationPanel.setLayout(icon_notificiationPanelLayout);
        icon_notificiationPanelLayout.setHorizontalGroup(
            icon_notificiationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, icon_notificiationPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(40, 40, 40))
        );
        icon_notificiationPanelLayout.setVerticalGroup(
            icon_notificiationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_notificiationPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout changeDynamicPanelLayout = new javax.swing.GroupLayout(changeDynamicPanel);
        changeDynamicPanel.setLayout(changeDynamicPanelLayout);
        changeDynamicPanelLayout.setHorizontalGroup(
            changeDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeDynamicPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(icon_notificiationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        changeDynamicPanelLayout.setVerticalGroup(
            changeDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeDynamicPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(icon_notificiationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        designdynamicPanel.setBackground(new java.awt.Color(235, 255, 255));
        designdynamicPanel.setPreferredSize(new java.awt.Dimension(342, 259));
        designdynamicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                designdynamicPanelMouseClicked(evt);
            }
        });

        icon_designPanel.setBackground(new java.awt.Color(0, 153, 153));
        icon_designPanel.setToolTipText("Customize design");
        icon_designPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_designPanelMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/005-monitor.png"))); // NOI18N

        javax.swing.GroupLayout icon_designPanelLayout = new javax.swing.GroupLayout(icon_designPanel);
        icon_designPanel.setLayout(icon_designPanelLayout);
        icon_designPanelLayout.setHorizontalGroup(
            icon_designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_designPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        icon_designPanelLayout.setVerticalGroup(
            icon_designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_designPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout designdynamicPanelLayout = new javax.swing.GroupLayout(designdynamicPanel);
        designdynamicPanel.setLayout(designdynamicPanelLayout);
        designdynamicPanelLayout.setHorizontalGroup(
            designdynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designdynamicPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(icon_designPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        designdynamicPanelLayout.setVerticalGroup(
            designdynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designdynamicPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(icon_designPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(changeDynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jSeparator3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volumedynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lockdynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(designdynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lockdynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volumedynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designdynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeDynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void icon_volumePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_volumePanelMouseClicked
        if(icon_volumePanel.isVisible()==true)
        {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(true); 
        icon_volumePanel.setEnabled(false);
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(true);
        icon_designPanel.setVisible(true);
        icon_lockPane.setVisible(true);
        icon_volumePanel.setVisible(false);
        }
        else {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(false);
        icon_designPanel.setVisible(false);
        icon_lockPane.setVisible(false);
        icon_volumePanel.setVisible(true);       
       }
    }//GEN-LAST:event_icon_volumePanelMouseClicked

    private void icon_lockPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_lockPaneMouseClicked
        if(icon_lockPane.isVisible()==true)
        {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(true); 
        icon_lockPane.setEnabled(false);
        icon_notificiationPanel.setVisible(true);
        icon_designPanel.setVisible(true);
        icon_lockPane.setVisible(false);
        icon_volumePanel.setVisible(true);
        }
        else {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(false);
        icon_designPanel.setVisible(false);
        icon_lockPane.setVisible(true);
        icon_volumePanel.setVisible(false); 
        }
    }//GEN-LAST:event_icon_lockPaneMouseClicked

    private void icon_designPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_designPanelMouseClicked
     if(icon_designPanel.isVisible()==true)
        {
        notification.setVisible(false); 
        design.setVisible(true); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_designPanel.setEnabled(false);
        icon_notificiationPanel.setVisible(true);
        icon_designPanel.setVisible(false);
        icon_lockPane.setVisible(true);
        icon_volumePanel.setVisible(true);
        }
        else {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(false);
        icon_designPanel.setVisible(true);
        icon_lockPane.setVisible(false);
        icon_volumePanel.setVisible(false); 
        }
    }//GEN-LAST:event_icon_designPanelMouseClicked

    private void volumedynamicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumedynamicPanelMouseClicked
           if(volume.isVisible()){
           icon_volumePanel.setVisible(true);
           volume.setVisible(false);
       }
    }//GEN-LAST:event_volumedynamicPanelMouseClicked

    private void icon_notificiationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_notificiationPanelMouseClicked
          if(icon_notificiationPanel.isVisible()==true)
        {
        notification.setVisible(true); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setEnabled(false);
        icon_notificiationPanel.setVisible(false);
        icon_designPanel.setVisible(true);
        icon_lockPane.setVisible(true);
        icon_volumePanel.setVisible(true);
        }
        else {
        notification.setVisible(false); 
        design.setVisible(false); 
        volume.setVisible(false); 
        lock.setVisible(false); 
        icon_notificiationPanel.setVisible(true);
        icon_designPanel.setVisible(false);
        icon_lockPane.setVisible(false);
        icon_volumePanel.setVisible(false); 
        }
    }//GEN-LAST:event_icon_notificiationPanelMouseClicked

    private void lockdynamicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockdynamicPanelMouseClicked
         if(lock.isVisible()){
           icon_lockPane.setVisible(true);
           lock.setVisible(false);
         }
    }//GEN-LAST:event_lockdynamicPanelMouseClicked

    private void changeDynamicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeDynamicPanelMouseClicked
         if(notification.isVisible()){
           icon_notificiationPanel.setVisible(true);
           notification.setVisible(false);
         }
    }//GEN-LAST:event_changeDynamicPanelMouseClicked

    private void designdynamicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designdynamicPanelMouseClicked
         if(design.isVisible()){
           icon_designPanel.setVisible(true);
           design.setVisible(false);
         }
    }//GEN-LAST:event_designdynamicPanelMouseClicked

    public Notification getNotification() {
        return notification;
    }

    public DesignPanel getDesign() {
        return design;
    }

    public VolumePanel getVolume() {
        return volume;
    }

    public lockPanel getLock() {
        return lock;
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel changeDynamicPanel;
    private javax.swing.JPanel designdynamicPanel;
    private javax.swing.JPanel icon_designPanel;
    private javax.swing.JPanel icon_lockPane;
    private javax.swing.JPanel icon_notificiationPanel;
    private javax.swing.JPanel icon_volumePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel lockdynamicPanel;
    private javax.swing.JPanel volumedynamicPanel;
    // End of variables declaration//GEN-END:variables
}
