/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.MyPanels.show;

import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import view.InputCheck;
import view.UserMenu;
import view.ViewLogic;

/**
 *
 *
 */
public class ShowWarehouseMore extends javax.swing.JPanel {
private static ViewLogic view;
private int  warehouseNumber;
private UserMenu um;
    /**
     * Creates new form ShowWarehouseMore
     */
    public ShowWarehouseMore(UserMenu um) {
        initComponents();
        view=ViewLogic.getInstance();
        this.um=um;
        icon_plus.setVisible(false);
        icon_remove.setVisible(false);
        partsTableLayeredPane.setVisible(false);
        vehicleLayeredPane.setVisible(false);
        Add_btn1.setVisible(false);
    }
public void setWarehouseNum(int warehouseNumber ){
    this.warehouseNumber=warehouseNumber;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        LayeredPane1 = new javax.swing.JLayeredPane();
        choiceComboBox = new javax.swing.JComboBox<>();
        partsTableLayeredPane = new javax.swing.JLayeredPane();
        resTableScrollPane2 = new javax.swing.JScrollPane();
        partsTable = new javax.swing.JTable();
        vehicleLayeredPane = new javax.swing.JLayeredPane();
        resTableScrollPane = new javax.swing.JScrollPane();
        vehiclesTable = new javax.swing.JTable();
        Add_btn1 = new javax.swing.JPanel();
        btn_name = new javax.swing.JLabel();
        icon_plus = new javax.swing.JLabel();
        icon_remove = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        amountSeparator = new javax.swing.JSeparator();
        amountLabel = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(235, 255, 255));

        choiceComboBox.setBackground(new java.awt.Color(0, 102, 102));
        choiceComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        choiceComboBox.setForeground(new java.awt.Color(255, 255, 255));
        choiceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one option", "Add Vehicle", "Add Part", "Remove Vehicle", "Remove Part" }));
        choiceComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceComboBoxItemStateChanged(evt);
            }
        });
        choiceComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                choiceComboBoxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choiceComboBoxMouseReleased(evt);
            }
        });

        LayeredPane1.setLayer(choiceComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPane1Layout = new javax.swing.GroupLayout(LayeredPane1);
        LayeredPane1.setLayout(LayeredPane1Layout);
        LayeredPane1Layout.setHorizontalGroup(
            LayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choiceComboBox, 0, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        LayeredPane1Layout.setVerticalGroup(
            LayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        resTableScrollPane2.setBackground(new java.awt.Color(235, 255, 255));

        partsTable.setAutoCreateRowSorter(true);
        partsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part Type Number", "Part Type Name", "Category", "Production Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        partsTable.setSelectionBackground(new java.awt.Color(76, 188, 188));
        partsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        partsTable.setShowHorizontalLines(false);
        partsTable.setShowVerticalLines(false);
        partsTable.getTableHeader().setReorderingAllowed(false);
        resTableScrollPane2.setViewportView(partsTable);
        partsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                try{
                    partsTable.getValueAt(partsTable.getSelectedRow(), 0);
                    amountLabel.setVisible(true);
                    amountLabel.setEnabled(true);
                    amountText.setVisible(true);
                    amountText.setEnabled(true);
                    amountSeparator.setVisible(true);
                    amountSeparator.setEnabled(true);
                }
                catch (IndexOutOfBoundsException e){
                    amountLabel.setVisible(false);
                    amountLabel.setEnabled(false);
                    amountText.setVisible(false);
                    amountText.setEnabled(false);
                    amountSeparator.setVisible(false);
                    amountSeparator.setEnabled(false);
                }
            }
        });

        partsTableLayeredPane.setLayer(resTableScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout partsTableLayeredPaneLayout = new javax.swing.GroupLayout(partsTableLayeredPane);
        partsTableLayeredPane.setLayout(partsTableLayeredPaneLayout);
        partsTableLayeredPaneLayout.setHorizontalGroup(
            partsTableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partsTableLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resTableScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        partsTableLayeredPaneLayout.setVerticalGroup(
            partsTableLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partsTableLayeredPaneLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(resTableScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        vehiclesTable.setAutoCreateRowSorter(true);
        vehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VIN", "Model Name", "Vehicle Type", "HP", "Top Speed", "Number of Seats", "Automatic", "Production Cost", "Entered Production", "Production Plan - Serial Number", "Production Plan Type - Serial Number", "Production Plan Type - Number of Slots", "Order Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vehiclesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        vehiclesTable.setSelectionBackground(new java.awt.Color(76, 188, 188));
        vehiclesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        vehiclesTable.getTableHeader().setReorderingAllowed(false);
        resTableScrollPane.setViewportView(vehiclesTable);

        vehicleLayeredPane.setLayer(resTableScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout vehicleLayeredPaneLayout = new javax.swing.GroupLayout(vehicleLayeredPane);
        vehicleLayeredPane.setLayout(vehicleLayeredPaneLayout);
        vehicleLayeredPaneLayout.setHorizontalGroup(
            vehicleLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleLayeredPaneLayout.createSequentialGroup()
                .addComponent(resTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        vehicleLayeredPaneLayout.setVerticalGroup(
            vehicleLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        Add_btn1.setBackground(new java.awt.Color(0, 102, 102));
        Add_btn1.setForeground(new java.awt.Color(255, 255, 255));
        Add_btn1.setPreferredSize(new java.awt.Dimension(202, 50));
        Add_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_btn1MouseClicked(evt);
            }
        });

        btn_name.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        btn_name.setForeground(new java.awt.Color(255, 255, 255));
        btn_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        icon_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/001-signs.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/MyPanels/show/Bundle"); // NOI18N
        icon_plus.setText(bundle.getString("ShowWarehouseMore.icon_plus.text")); // NOI18N

        icon_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/003-interface.png"))); // NOI18N
        icon_remove.setText(bundle.getString("ShowWarehouseMore.icon_remove.text")); // NOI18N

        javax.swing.GroupLayout Add_btn1Layout = new javax.swing.GroupLayout(Add_btn1);
        Add_btn1.setLayout(Add_btn1Layout);
        Add_btn1Layout.setHorizontalGroup(
            Add_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_btn1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(icon_remove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_name, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icon_plus)
                .addContainerGap())
        );
        Add_btn1Layout.setVerticalGroup(
            Add_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_btn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Add_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_btn1Layout.createSequentialGroup()
                        .addComponent(btn_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(Add_btn1Layout.createSequentialGroup()
                        .addComponent(icon_plus, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(Add_btn1Layout.createSequentialGroup()
                        .addComponent(icon_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        amountText.setBackground(new java.awt.Color(235, 255, 255));
        amountText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        amountText.setBorder(null);
        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });
        amountText.setVisible(false);
        amountText.setEnabled(false);

        amountSeparator.setForeground(new java.awt.Color(102, 102, 102));
        amountSeparator.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        amountSeparator.setVisible(false);
        amountSeparator.setEnabled(false);

        amountLabel.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(87, 84, 84));
        amountLabel.setText(bundle.getString("ShowWarehouseMore.amountLabel.text")); // NOI18N
        amountLabel.setVisible(false);
        amountLabel.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountSeparator)
                            .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Add_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vehicleLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partsTableLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(partsTableLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(amountSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Add_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceComboBoxItemStateChanged
        String txt= (String)choiceComboBox.getSelectedItem();
        if(txt.equals("Add Vehicle") || txt.equals("הוסף רכב")){
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            btn_name.setText("Add");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                btn_name.setText("הוסף");
            icon_plus.setVisible(true);
            icon_remove.setVisible(false);
            partsTableLayeredPane.setVisible(false);
            vehicleLayeredPane.setVisible(true);
            Add_btn1.setVisible(true);
            view.addVehicleToWarehouse(vehiclesTable, warehouseNumber,um.getLanguageComboBox());
            amountLabel.setVisible(false);
              amountLabel.setEnabled(false);
              amountText.setVisible(false);
              amountText.setEnabled(false);
              amountSeparator.setVisible(false);
              amountSeparator.setEnabled(false);
               amountText.setText("");
            
        }
        if(txt.equals("Add Part") || txt.equals("הוסף חלק")){
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            btn_name.setText("Add");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                btn_name.setText("הוסף");
            icon_plus.setVisible(true);
            icon_remove.setVisible(false);
            partsTableLayeredPane.setVisible(true);
            vehicleLayeredPane.setVisible(false);
            Add_btn1.setVisible(true);
            view.addPartTypeToWarehouse(partsTable, warehouseNumber,um.getLanguageComboBox());
             amountText.setText("");
        }
        if(txt.equals("Remove Part") || txt.equals("הסר חלק")){
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            btn_name.setText("Remove");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                btn_name.setText("הסר");
            icon_plus.setVisible(false);
            icon_remove.setVisible(true);
            partsTableLayeredPane.setVisible(true);
            vehicleLayeredPane.setVisible(false);
            Add_btn1.setVisible(true);
            view.removePartTypeFromWarehouse(partsTable, warehouseNumber,um.getLanguageComboBox());
             amountText.setText("");
        }
        if(txt.equals("Remove Vehicle") || txt.equals("הסר רכב")){
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            btn_name.setText("Remove");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                btn_name.setText("הסר");
            icon_plus.setVisible(false);
            icon_remove.setVisible(true);
            partsTableLayeredPane.setVisible(false);
            vehicleLayeredPane.setVisible(true);
            Add_btn1.setVisible(true);
            view.removeVehicleFromWarehouse(vehiclesTable, warehouseNumber,um.getLanguageComboBox());
            amountLabel.setVisible(false);
              amountLabel.setEnabled(false);
              amountText.setVisible(false);
              amountText.setEnabled(false);
              amountSeparator.setVisible(false);
              amountSeparator.setEnabled(false);
               amountText.setText("");
        }
        if (txt.equals("Choose one option") || txt.equals("בחר אפשרות אחת")){
            Add_btn1.setVisible(false);
            partsTableLayeredPane.setVisible(false);
            vehicleLayeredPane.setVisible(false);
            amountLabel.setVisible(false);
              amountLabel.setEnabled(false);
              amountText.setVisible(false);
              amountText.setEnabled(false);
              amountSeparator.setVisible(false);
              amountSeparator.setEnabled(false);
               amountText.setText("");
        }
    }//GEN-LAST:event_choiceComboBoxItemStateChanged

    private void choiceComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiceComboBoxMousePressed

    }//GEN-LAST:event_choiceComboBoxMousePressed

    private void choiceComboBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiceComboBoxMouseReleased

    }//GEN-LAST:event_choiceComboBoxMouseReleased

    private void Add_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_btn1MouseClicked

        if((btn_name.getText().equals("Remove") && choiceComboBox.getSelectedItem().equals("Remove Vehicle")) || (btn_name.getText().equals("הסר") && choiceComboBox.getSelectedItem().equals("הסר רכב"))){
            boolean bool=false;
            if (vehiclesTable.getSelectedRow()==-1 ){
                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            JOptionPane.showMessageDialog(null, "You must select a vehicle from the table!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך לבחור רכב מהטבלה!");
            }
            else
            {
                Object[] options = {"Yes","No"};
                Object[] hebOptions = {"כן","לא"};
            int n=0;
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              n = JOptionPane.showOptionDialog(null, "Are you sure you want to proceed?","Removing confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[1]);
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              n = JOptionPane.showOptionDialog(null, "האם אתה בטוח שברצונך להמשיך?","אימות הסרה",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,hebOptions,hebOptions[1]);
                if (n==0)

                {
                    bool=view.controller.removeVehicleFromWarehouse(vehiclesTable.getValueAt(vehiclesTable.getSelectedRow(), 0).toString(),warehouseNumber);
                    if (bool==true)
                    {
                        Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                        JOptionPane.showMessageDialog(null, "Vehicle removed successfully!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "הרכב הוסר בהצלחה!");
                        view.removeVehicleFromWarehouse(vehiclesTable, warehouseNumber,um.getLanguageComboBox());

                    }
                    else{
                        Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, "Vehicle was not removed!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "הרכב לא הוסר!");
                    }
                }
            }
        }
        else if((btn_name.getText().equals("Remove") && choiceComboBox.getSelectedItem().equals("Remove Part")) || (btn_name.getText().equals("הסר") && choiceComboBox.getSelectedItem().equals("הסר חלק"))){
            boolean bool=false;
            if (partsTable.getSelectedRow()==-1 ){
                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            JOptionPane.showMessageDialog(null, "You must select a part from the table!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך לבחור חלק מהטבלה!");
            }
           else if (amountText.getText().isEmpty()){
               Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                JOptionPane.showMessageDialog(null, "You must input the desired quantity to be removed!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך להזין את כמות החלקים הרצויה!");
                amountText.grabFocus();
            }
            else
            {
                Integer partnumber=0;
                partnumber=InputCheck.TryConvertingStringtoInteger(amountText.getText(), partnumber);
                if (partnumber==null)
                {
                    Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()-1) + "input must be a number!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()) + " חייב להיות מספר!");
                    amountText.grabFocus();
                }
                else if (partnumber!=null && partnumber<=0)
                {
                    Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()-1) + "input must be a positive number!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()) + " חייב להיות מספר חיובי!");
                    amountText.grabFocus();
                }
                else if (partnumber!=null && partnumber>0)
                {
                    Object[] options = {"Yes","No"};
                    Object[] hebOptions = {"כן","לא"};
            int n=0;
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              n = JOptionPane.showOptionDialog(null, "Are you sure you want to proceed?","Removing confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[1]);
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              n = JOptionPane.showOptionDialog(null, "האם אתה בטוח שברצונך להמשיך?","אימות הסרה",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,hebOptions,hebOptions[1]);
                    if (n==0)
                    {
                        bool=view.controller.removePartTypeFromWarehouse((Integer)partsTable.getValueAt(partsTable.getSelectedRow(),0),partnumber,warehouseNumber);
                        
                        if (bool==true)
                        {
                            Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                            JOptionPane.showMessageDialog(null, "Part removed successfully!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "החלק הוסר בהצלחה!");
                            view.removePartTypeFromWarehouse(partsTable, warehouseNumber,um.getLanguageComboBox());
                            amountText.setText("");
                        }
                        else{
                            Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                            JOptionPane.showMessageDialog(null, "You may remove a maximum of " + view.model.getWarehouses().get(warehouseNumber).getParts().get(view.model.getParts().get((Integer)partsTable.getValueAt(partsTable.getSelectedRow(),0))) + " parts!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "ניתן להסיר כמות מקסימאלית של " + view.model.getWarehouses().get(warehouseNumber).getParts().get(view.model.getParts().get((Integer)partsTable.getValueAt(partsTable.getSelectedRow(),0))) + " חלקים!");
                        }
                    }
                }
            }
        }
        else if((btn_name.getText().equals("Add") && choiceComboBox.getSelectedItem().equals("Add Vehicle")) || (btn_name.getText().equals("הוסף") && choiceComboBox.getSelectedItem().equals("הוסף רכב"))){
            boolean bool=false;
            if (vehiclesTable.getSelectedRow()==-1 ){
                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            JOptionPane.showMessageDialog(null, "You must select a vehicle from the table!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך לבחור רכב מהטבלה!");
            }
            else
            {
                Object[] options = {"Yes","No"};
                Object[] hebOptions = {"כן","לא"};
            int n=0;
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              n = JOptionPane.showOptionDialog(null, "Are you sure you want to proceed?","Adding confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[1]);
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              n = JOptionPane.showOptionDialog(null, "האם אתה בטוח שברצונך להמשיך?","אימות הוספה",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,hebOptions,hebOptions[1]);
                if (n==0)

                {
                    bool=view.controller.addVehicleToWarehouse(vehiclesTable.getValueAt(vehiclesTable.getSelectedRow(), 0).toString(),warehouseNumber);
                    if (bool==true)
                    {
                        Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                        JOptionPane.showMessageDialog(null, "Vehicle added successfully!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "הרכב הוסף בהצלחה!");
                        view.addVehicleToWarehouse(vehiclesTable, warehouseNumber,um.getLanguageComboBox());

                    }
                    else{
                        Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, "You have reached max vehicles stored!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "הגעת למכסת כמות הרכבים לאחסון!");
                    }
                }
            }
        }
        else if((btn_name.getText().equals("Add") && choiceComboBox.getSelectedItem().equals("Add Part")) || (btn_name.getText().equals("הוסף") && choiceComboBox.getSelectedItem().equals("הוסף חלק"))){
            boolean bool=false;
            if (partsTable.getSelectedRow()==-1 ){
                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
            JOptionPane.showMessageDialog(null, "You must select a part from the table!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך לבחור חלק מהטבלה!");
            }
           else if (amountText.getText().isEmpty()){
               Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                JOptionPane.showMessageDialog(null, "You must input the desired quantity to be added!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "עליך להזין את כמות החלקים הרצויה!");
                amountText.grabFocus();
            }
            else
            {
                Integer partnumber=0;
                partnumber=InputCheck.TryConvertingStringtoInteger(amountText.getText(), partnumber);
                if (partnumber==null)
                {
                    Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()-1) + "input must be a number!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()) + " חייב להיות מספר!");
                    amountText.grabFocus();
                }
                else if (partnumber!=null && partnumber<=0)
                {
                    Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                    JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()-1) + "input must be a positive number!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, amountLabel.getText().substring(0, amountLabel.getText().length()) + " חייב להיות מספר חיובי!");
                    amountText.grabFocus();
                }
                else if (partnumber!=null && partnumber>0)
                {
                    Object[] options = {"Yes","No"};
                    Object[] hebOptions = {"כן","לא"};
            int n=0;
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
              n = JOptionPane.showOptionDialog(null, "Are you sure you want to proceed?","Adding confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[1]);
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
              n = JOptionPane.showOptionDialog(null, "האם אתה בטוח שברצונך להמשיך?","אימות הוספה",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,hebOptions,hebOptions[1]);
                    if (n==0)
                    {
                       
                        bool=view.controller.addPartTypeToWarehouse((Integer)partsTable.getValueAt(partsTable.getSelectedRow(),0),partnumber,warehouseNumber);
                        if (bool==true)
                        {
                            Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                            JOptionPane.showMessageDialog(null, "Part added successfully!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "החלק הוסף בהצלחה!");
                            view.addPartTypeToWarehouse(partsTable, warehouseNumber,um.getLanguageComboBox());
                            amountText.setText("");
                        }
                        else{
                            Integer currentPartsNum=0;
                            for (Integer num: view.model.getWarehouses().get(warehouseNumber).getParts().values())
                                currentPartsNum=currentPartsNum+num;
                            if (view.model.getWarehouses().get(warehouseNumber).getMaxPartsStored()-currentPartsNum==0){
                                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                                JOptionPane.showMessageDialog(null, "You have reached the maximum parts stored!");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "הגעת למכסת כמות החלקים לאחסון!");
                            }
                            else{
                                Toolkit.getDefaultToolkit().beep();
            if (um.getLanguageComboBox().getSelectedItem().equals("English") || um.getLanguageComboBox().getSelectedItem().equals("Choose a language"))
                            JOptionPane.showMessageDialog(null, "You may add only " + (view.model.getWarehouses().get(warehouseNumber).getMaxPartsStored()-currentPartsNum) + " more parts! ");
            else if (um.getLanguageComboBox().getSelectedItem().equals("עברית"))
                JOptionPane.showMessageDialog(null, "ניתן להוסיף רק עוד " + (view.model.getWarehouses().get(warehouseNumber).getMaxPartsStored()-currentPartsNum) + " חלקים! ");
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_Add_btn1MouseClicked

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
       vehiclesTable.clearSelection();
       partsTable.clearSelection();
       choiceComboBox.setSelectedIndex(0);
       amountText.setText("");
    }//GEN-LAST:event_formComponentHidden
    public JTable getPartsTable(){
        return partsTable;
    }
    public JTable getVehiclesTable(){
        return vehiclesTable;
    }

    public JLabel getAmountLabel() {
        return amountLabel;
    }

    public JLabel getBtn_name() {
        return btn_name;
    }

    public JComboBox<String> getChoiceComboBox() {
        return choiceComboBox;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_btn1;
    private javax.swing.JLayeredPane LayeredPane1;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JSeparator amountSeparator;
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel btn_name;
    private javax.swing.JComboBox<String> choiceComboBox;
    private javax.swing.JLabel icon_plus;
    private javax.swing.JLabel icon_remove;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable partsTable;
    private javax.swing.JLayeredPane partsTableLayeredPane;
    private javax.swing.JScrollPane resTableScrollPane;
    private javax.swing.JScrollPane resTableScrollPane2;
    private javax.swing.JLayeredPane vehicleLayeredPane;
    private javax.swing.JTable vehiclesTable;
    // End of variables declaration//GEN-END:variables
}
