/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.ControllerLogic;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import utils.Constants;
import utils.MyFileLogWriter;
import java.io.Serializable;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 *
 */
public class Login extends javax.swing.JFrame implements Serializable {
 private static final long serialVersionUID = 1L;
 private static ViewLogic view;

    /**
     * Creates new form Log
     */
    public Login() {
        initComponents();
        view=ViewLogic.getInstance();
        Locale.setDefault(new Locale("en","US"));
        languageComboBox.setSelectedIndex(0);
        emptyFields(user, password, login);
        user.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneLogin = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        user = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        forgotPassword = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox<>();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPaneLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desktopPaneLoginMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(76, 188, 188));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/001-transport.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S.A Systems");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(2, 35, 66));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/001-user.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        user.setBackground(new java.awt.Color(2, 35, 66));
        user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user.setForeground(new java.awt.Color(204, 204, 204));
        user.setText("Username");
        user.setToolTipText("Username");
        user.setBorder(null);
        user.setCaretColor(new java.awt.Color(255, 255, 255));
        user.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMousePressed(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(jPanel2.getBackground());
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        forgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword.setText("Forgot Password?");
        forgotPassword.setToolTipText("");
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(forgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(forgotPassword)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        languageComboBox.setBackground(jPanel2.getBackground());
        languageComboBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        languageComboBox.setForeground(new java.awt.Color(255, 255, 255));
        languageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "עברית" }));
        languageComboBox.setBorder(null);
        languageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboBoxActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(2, 51, 99));
        login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(null);
        login.setEnabled(false);
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
        };
        user.getDocument().addDocumentListener(docListener);
        password.getDocument().addDocumentListener(docListener);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });

        password.setBackground(new java.awt.Color(2, 35, 66));
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Password");
        password.setToolTipText("Password");
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.setEchoChar('\u0000');
        password.setMaximumSize(new java.awt.Dimension(400, 400));
        password.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(user)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jSeparator4.setVisible(false);
        login.getAccessibleContext().setAccessibleParent(desktopPaneLogin);

        desktopPaneLogin.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPaneLogin.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLoginLayout = new javax.swing.GroupLayout(desktopPaneLogin);
        desktopPaneLogin.setLayout(desktopPaneLoginLayout);
        desktopPaneLoginLayout.setHorizontalGroup(
            desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        desktopPaneLoginLayout.setVerticalGroup(
            desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        view.ForgotPassword(this, languageComboBox);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
          if (login.isEnabled())
        loginActionPerformed(evt);
    }//GEN-LAST:event_userActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                    
           Boolean bool;
           String pass=password.getText();
           view.Verification(user.getText(),pass,this,languageComboBox);
    }//GEN-LAST:event_loginActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
          int key=evt.getKeyCode();
          ActionEvent ae = new ActionEvent(evt.getSource(), evt.getID(), evt.paramString());
          if(key==KeyEvent.VK_ENTER && login.isEnabled())        
          loginActionPerformed(ae);
            login.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
    }//GEN-LAST:event_loginKeyPressed

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
         cleanUserField();
    }//GEN-LAST:event_userFocusGained

    private void userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyTyped
       cleanUserField();
    }//GEN-LAST:event_userKeyTyped

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
       
       Font font= new Font("Tahoma", Font.BOLD, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
       forgotPassword.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
       Font font= new Font("Dialog", Font.PLAIN, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, -1);
       forgotPassword.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jPanel3MouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        try {
            view.serialization(Constants.Ser_FileName);
        } catch (IOException ex) {
        }
        MyFileLogWriter.saveLogFile();
    }//GEN-LAST:event_formWindowClosing

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
         if (user.getText().isEmpty())
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
              user.setForeground(new Color(204,204,204));
              user.setText("Username");
            }
            else if (languageComboBox.getSelectedItem().equals("עברית")){
              user.setForeground(new Color(204,204,204));
              user.setText("שם משתמש");
            }
        }
    }//GEN-LAST:event_userFocusLost

    private void desktopPaneLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopPaneLoginMousePressed
     if (user.isFocusOwner() && user.getText().isEmpty())
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            user.setForeground(new Color(204,204,204));
            user.setText("Username");
            }
            else if (languageComboBox.getSelectedItem().equals("עברית")){
                user.setForeground(new Color(204,204,204));
                user.setText("שם משתמש");
            }
        }
        else if (password.isFocusOwner() && password.getPassword().length<1)
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            password.setForeground(new Color(204,204,204));
            password.setEchoChar('\u0000');
            password.setText("Password");
            }
            else if (languageComboBox.getSelectedItem().equals("עברית")){
                password.setForeground(new Color(204,204,204));
                password.setEchoChar('\u0000');
                password.setText("סיסמא");
            }
        }
    }//GEN-LAST:event_desktopPaneLoginMousePressed

    private void forgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseEntered
  
       Font font= new Font("Tahoma", Font.BOLD, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
       forgotPassword.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_forgotPasswordMouseEntered

    private void forgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseExited
       Font font= new Font("Dialog", Font.PLAIN, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, -1);
       forgotPassword.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_forgotPasswordMouseExited

    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseClicked
        view.ForgotPassword(this,languageComboBox);
    }//GEN-LAST:event_forgotPasswordMouseClicked

    private void languageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboBoxActionPerformed
        
       if (languageComboBox.getSelectedItem().equals("עברית"))
       {
           user.setText("שם משתמש");
           password.setText("סיסמא");
           cleanUserField();
           cleanPasswordField();
           Locale l = new Locale("iw", "IL");
           ResourceBundle r = ResourceBundle.getBundle("view/Bundle",l);
           user.setText(r.getString("Login.user.text"));
           password.setText(r.getString("Login.password.text"));
           login.setText(r.getString("Login.login.text"));
           forgotPassword.setText(r.getString("Login.forgotPassword.text"));
           user.setToolTipText(r.getString("Login.user.toolTipText"));
           password.setToolTipText(r.getString("Login.password.toolTipText"));
           forgotPassword.setToolTipText(r.getString("Login.forgotPassword.toolTipText"));
       }
       else if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language"))
       {
           user.setText("Username");
           password.setText("Password");
           cleanUserField();
           cleanPasswordField();
           Locale l = new Locale("en", "US");
           ResourceBundle r = ResourceBundle.getBundle("view/Bundle",l);
           user.setText(r.getString("Login.user.text"));
           password.setText(r.getString("Login.password.text"));
           login.setText(r.getString("Login.login.text"));
           forgotPassword.setText(r.getString("Login.forgotPassword.text"));
           user.setToolTipText(r.getString("Login.user.toolTipText"));
           password.setToolTipText(r.getString("Login.password.toolTipText"));
           forgotPassword.setToolTipText(r.getString("Login.forgotPassword.toolTipText"));
       }
       user.setForeground(new Color(204,204,204));
       password.setForeground(new Color(204,204,204));
       password.setEchoChar('\u0000');
       login.setEnabled(false);
       login.setBackground(new Color(2,51,99)); 
    }//GEN-LAST:event_languageComboBoxActionPerformed

    private void userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMousePressed

    }//GEN-LAST:event_userMousePressed

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
         if (password.getPassword().length<1)
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            password.setForeground(new Color(204,204,204));
            password.setEchoChar('\u0000');
            password.setText("Password");
            }
            else if (languageComboBox.getSelectedItem().equals("עברית")){
                password.setForeground(new Color(204,204,204));
                password.setEchoChar('\u0000');
                password.setText("סיסמא");
            }
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
      
    }//GEN-LAST:event_passwordMousePressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        if (login.isEnabled())
        loginActionPerformed(evt);
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        cleanPasswordField();
    }//GEN-LAST:event_passwordKeyTyped

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
         cleanPasswordField();
    }//GEN-LAST:event_passwordFocusGained

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        cleanPasswordField();
    }//GEN-LAST:event_passwordMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
         cleanUserField();
    }//GEN-LAST:event_userMouseClicked
 
    private void emptyFields(JTextField user, JPasswordField password, JButton login){
             if (user.getText().length()<4 || user.getForeground().equals(new Color(204,204,204)) || password.getPassword().length<4 || password.getForeground().equals(new Color(204,204,204))){
                login.setEnabled(false);
                login.setBackground(new Color(2,51,99)); 
             }
             else{
                login.setEnabled(true);
                login.setBackground(new Color(76,188,188)); 
             }
    }
    
    private void cleanUserField()
    {
        int r,g,b;
        r=user.getForeground().getRed();
        g=user.getForeground().getGreen();
        b=user.getForeground().getBlue();
        if (user.getText().equals("Username") && (r==204 && g==204 && b==204) || user.getText().equals("שם משתמש") && (r==204 && g==204 && b==204))
            user.setText("");
        user.setForeground(Color.WHITE);
    }
    private void cleanPasswordField()
    {
         int r,g,b;
       String pass="Password";
       String passHe="סיסמא";
        char[] arr=pass.toCharArray();
        char[] arrHe=passHe.toCharArray();
        Font font= new Font("Tahoma", Font.PLAIN, 13);
        r=password.getForeground().getRed();
        g=password.getForeground().getGreen();
        b=password.getForeground().getBlue();
        if (Arrays.equals(password.getPassword(), arr) && (r==204 && g==204 && b==204) || Arrays.equals(password.getPassword(), arrHe) && (r==204 && g==204 && b==204))
            password.setText("");
        password.setForeground(Color.WHITE);
        password.setEchoChar('\u25cf');
       password.setFont(font);
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPaneLogin;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    protected javax.swing.JComboBox<String> languageComboBox;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
